#!/usr/bin/env bash

#PBS -l nodes=1:ppn=8
#PBS -l walltime=00:30:00
#PBS -l mem=2gb

# "# command" was used as a placeholder where a line of code should be inserted

# Load the necessary modules
module load FastQC/0.11.9-Java-11
module load parallel-fastq-dump/0.6.6-GCCcore-9.3.0-SRA-Toolkit-3.0.0-Python-3.8.2

# Change to the directory you are working in 
cd /user/gent/439/vsc43966/Prac_3_AHTA

# Make a directory to store fastqc output
mkdir fastqc

# For loop over all samples
for ID in SRR401413 SRR401414 SRR401415 SRR401422 SRR401423 SRR401424
# This for loop will loop over the variables after "in" each time attributing the value SRRXXX as to $ID
do 
	# Echo the ID you are processing
	echo $ID
	
	# Load the first (-X 500000) 500,000 reads for the ID (--sra-id $ID) you are processing using 8 cores (--threads 8)
	parallel-fastq-dump --sra-id $ID --threads 8 -X 500000
	
	# Perform QC with fastqc on the raw reads outputting everything in the fastqc folder (--outdir fastqc)
	fastqc --outdir fastqc $ID.fastq
	
	# Remove fastq files to reduce disk usage
	rm $ID.fastq
done

echo "SRR401413"
echo "SRR401414"
echo "SRR401415"
echo "SRR401422"
echo "SRR401423"
echo "SRR401424"
